// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZR_tuP-Xp6MxuA6IfC8M8j1bBAYlyJDU',
    appId: '1:343442679256:web:d4dff2a2a539d4413afead',
    messagingSenderId: '343442679256',
    projectId: 'increment-74553',
    authDomain: 'increment-74553.firebaseapp.com',
    storageBucket: 'increment-74553.appspot.com',
    measurementId: 'G-YK075596J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQO9wTnE2DLNEOeT8CC31V8jgyRY3cJZw',
    appId: '1:343442679256:android:21f128c16c1d766d3afead',
    messagingSenderId: '343442679256',
    projectId: 'increment-74553',
    storageBucket: 'increment-74553.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDi-TxF5K3S8TLv9VYGSEzlH97wmazYuI',
    appId: '1:343442679256:ios:6f3b75d880c98cfb3afead',
    messagingSenderId: '343442679256',
    projectId: 'increment-74553',
    storageBucket: 'increment-74553.appspot.com',
    iosBundleId: 'com.example.manojTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDi-TxF5K3S8TLv9VYGSEzlH97wmazYuI',
    appId: '1:343442679256:ios:6f3b75d880c98cfb3afead',
    messagingSenderId: '343442679256',
    projectId: 'increment-74553',
    storageBucket: 'increment-74553.appspot.com',
    iosBundleId: 'com.example.manojTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZR_tuP-Xp6MxuA6IfC8M8j1bBAYlyJDU',
    appId: '1:343442679256:web:6d18e339ff8f85e93afead',
    messagingSenderId: '343442679256',
    projectId: 'increment-74553',
    authDomain: 'increment-74553.firebaseapp.com',
    storageBucket: 'increment-74553.appspot.com',
    measurementId: 'G-658Q9KT7YP',
  );
}
